$(document).ready(function(){
  $("[class*='card-']").hide();
  $("[class*='btn']").hide();
// UI / UX
  $("#fishing_skill_btn").click(function(){
    $("[class*='btn']").fadeOut("slow");
    $("[class*='card-']").fadeOut("fast");
    $("[id*='-fish']").fadeIn("slow");
    $("[id*='fish_btn']").fadeIn("fast");
  });
  $("#fighting_skill_btn").click(function(){
    $("[class*='btn']").fadeOut("slow");
    $("[class*='card-']").fadeOut("fast");
    $("[id*='-fight']").fadeIn("slow");
  });
  $("#mining_skill_btn").click(function(){
    $("[class*='btn']").fadeOut("slow");
    $("[class*='card-']").fadeOut("fast");
    $("[id*='-mine']").fadeIn("slow");
  });
  $("#foraging_skill_btn").click(function(){
    $("[class*='btn']").fadeOut("slow");
    $("[class*='card-']").fadeOut("fast");
    $("[id*='-forage']").fadeIn("slow");
  });
  $("#farming_skill_btn").click(function(){
    $("[class*='btn']").fadeOut("slow");
    $("[class*='card-']").fadeOut("fast");
    $("[id*='-farm']").fadeIn("slow");
  });


  // fishing UX scripts
  $("#rivers_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='rivers']").show()
    $("[class*='every']").show()
  });
  $("#lake_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='lake']").show()
    $("[class*='every']").show()
  });
  $("#ocean_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='ocean']").show()
    $("[class*='every']").show()
  });
  $("#else_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='else']").show()
    $("[class*='every']").show()
  });

  $("#spring_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("#[class*='spring']").show();
    $("#[class*='allyr']").show();
  });
  $("#summer_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("#[class*='summer']").show();
    $("#[class*='allyr']").show();
  });
  $("#fall_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("#[class*='fall']").show();
    $("#[class*='allyr']").show();
  });
  $("#winter_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("#[class*='winter']").show();
    $("#[class*='allyr']").show();
  });

  $("#sunny_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='sunny']").show()
  });
  $("#rainy_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='rainy']").show();
    $("[class*='any']").show();
  });
  $("#morn_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='morn']").show()
    $("[class*='any']").show()
  });
  $("#even_fish_btn").click(function(){
    $("[class*='card-']").hide()
    $("[class*='even']").show();
    $("[class*='any']").show();
  });

});
